name: Testing

on: [pull_request]

jobs:
  testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant script run permission
        run: chmod +x ./scripts/testing.sh
      - name: Run testing script
        run: ./scripts/testing.sh